<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Pre-Build PCs
            [
                'name' => 'TechForge Obsidian X',
                'category' => 'Prebuilt Desktops',
                'brand' => 'TechForge Forge',
                'processor' => 'AMD Ryzen 7',
                'specs' => 'RYZEN 7 7800X3D | RTX 4080 SUPER',
                'price' => 145000,
                'rating' => 4.9,
                'image_url' => 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'badge' => 'BEST SELLER',
                'is_sold_out' => false,
                'tag' => 'Pre-Build',
                'os' => 'Windows 11 Home',
                'cpu' => 'AMD Ryzen 7 7800X3D',
                'gpu' => 'NVIDIA RTX 4080 SUPER 16GB',
                'ram' => '32GB DDR5-6000MHz',
                'storage' => '2TB NVMe M.2 SSD',
                'forge_points' => 1450,
                'shipping_status' => 'Free Shipping',
                'promo_tag' => 'SALE',
                'original_price' => 155000,
                'motherboard' => 'ASUS ROG Crosshair X670E Hero',
                'psu' => 'Corsair RM1000x 1000W',
                'case' => 'Lian Li O11 Dynamic EVO',
                'cooler' => 'NZXT Kraken 360',
            ],
            [
                'name' => 'ROG Strix G15',
                'category' => 'Prebuilt Desktops',
                'brand' => 'ASUS ROG',
                'processor' => 'AMD Ryzen 9',
                'specs' => 'RYZEN 9 7900X | RTX 4080',
                'price' => 180000,
                'rating' => 4.8,
                'image_url' => 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'badge' => 'SAVE 10%',
                'is_sold_out' => false,
                'tag' => 'Pre-Build',
                'os' => 'Windows 11 Pro',
                'cpu' => 'AMD Ryzen 9 7900X',
                'gpu' => 'NVIDIA RTX 4080 16GB',
                'ram' => '64GB DDR5-5600MHz',
                'storage' => '2TB Gen4 NVMe SSD',
                'forge_points' => 1800,
                'shipping_status' => 'Free Shipping',
                'promo_tag' => null,
                'original_price' => null,
                'motherboard' => 'ASUS ROG Crosshair X670E Hero',
                'psu' => 'Corsair RM1000x 1000W',
                'case' => 'Lian Li O11 Dynamic EVO',
                'cooler' => 'NZXT Kraken 360',
            ],
            [
                'name' => 'Lenovo Legion Tower 5i',
                'category' => 'Prebuilt Desktops',
                'brand' => 'Lenovo Legion',
                'processor' => 'Intel Core i7',
                'specs' => 'CORE I7-13700F | RTX 4060 Ti',
                'price' => 85000,
                'rating' => 4.6,
                'image_url' => 'https://images.unsplash.com/photo-1624705002806-5d72df19c3ad?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'badge' => null,
                'is_sold_out' => true,
                'tag' => 'Pre-Build',
                'os' => 'Windows 11 Home',
                'cpu' => 'Intel Core i7-13700F',
                'gpu' => 'NVIDIA RTX 4060 Ti 8GB',
                'ram' => '16GB DDR5-5200MHz',
                'storage' => '1TB NVMe SSD',
                'forge_points' => 850,
                'shipping_status' => 'Calculated at Checkout',
                'promo_tag' => 'LOW STOCK',
                'original_price' => 89000,
                'motherboard' => 'MSI MAG B650 TOMAHAWK WIFI',
                'psu' => 'Seasonic 650W',
                'case' => 'Lian Li O11 Dynamic EVO',
                'cooler' => 'NZXT Kraken 360',
            ],

            // Custom Build PCs
            [
                'name' => 'TechForge Quantum',
                'category' => 'Custom Builds',
                'brand' => 'TechForge Forge',
                'processor' => 'Intel Core i5',
                'specs' => 'CORE I5-13600K | RTX 4070 TI',
                'price' => 112500,
                'rating' => 4.7,
                'image_url' => 'https://images.unsplash.com/photo-1547082299-de196ea013d6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'badge' => null,
                'is_sold_out' => false,
                'tag' => 'Custom Build',
                'os' => 'Windows 11 Pro',
                'cpu' => 'Intel Core i5-13600K',
                'gpu' => 'NVIDIA RTX 4070 Ti 12GB',
                'ram' => '32GB DDR5-5600MHz',
                'storage' => '2TB NVMe M.2 SSD',
                'forge_points' => 1125,
                'shipping_status' => 'Free Shipping',
                'promo_tag' => null,
                'original_price' => null,
                'motherboard' => 'MSI MAG B650 TOMAHAWK WIFI',
                'psu' => 'Seasonic 650W',
                'case' => 'Lian Li O11 Dynamic EVO',
                'cooler' => 'NZXT Kraken 360',
            ],
            [
                'name' => 'TechForge Zenith Pro',
                'category' => 'Custom Builds',
                'brand' => 'TechForge Forge',
                'processor' => 'Intel Core i9',
                'specs' => 'CORE I9-14900K | RTX 4090',
                'price' => 235000,
                'rating' => 5.0,
                'image_url' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'badge' => 'NEW ARRIVAL',
                'is_sold_out' => false,
                'tag' => 'Custom Build',
                'os' => 'Windows 11 Pro',
                'cpu' => 'Intel Core i9-14900K',
                'gpu' => 'NVIDIA RTX 4090 24GB',
                'ram' => '64GB DDR5-6400MHz',
                'storage' => '4TB Gen4 NVMe M.2',
                'forge_points' => 2350,
                'shipping_status' => 'Free Shipping',
                'promo_tag' => 'LIMITED',
                'original_price' => 250000,
                'motherboard' => 'ASUS ROG Crosshair X670E Hero',
                'psu' => 'Corsair RM1000x 1000W',
                'case' => 'Lian Li O11 Dynamic EVO',
                'cooler' => 'NZXT Kraken 360',
            ],
            [
                'name' => 'TechForge Nova',
                'category' => 'Custom Builds',
                'brand' => 'TechForge Forge',
                'processor' => 'AMD Ryzen 5',
                'specs' => 'RYZEN 5 7600X | RTX 4060',
                'price' => 65000,
                'rating' => 4.5,
                'image_url' => 'https://images.unsplash.com/photo-1589149098258-3e9102cd63d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'badge' => null,
                'is_sold_out' => false,
                'tag' => 'Custom Build',
                'os' => 'Windows 11 Home',
                'cpu' => 'AMD Ryzen 5 7600X',
                'gpu' => 'NVIDIA RTX 4060 8GB',
                'ram' => '16GB DDR5-5200MHz',
                'storage' => '1TB NVMe M.2',
                'forge_points' => 650,
                'shipping_status' => 'Calculated at Checkout',
                'promo_tag' => null,
                'original_price' => null,
                'motherboard' => 'MSI MAG B650 TOMAHAWK WIFI',
                'psu' => 'Seasonic 650W',
                'case' => 'Lian Li O11 Dynamic EVO',
                'cooler' => 'NZXT Kraken 360',
            ]
        ];

        foreach ($products as $product) {
            \App\Models\Product::create($product);
        }
    }
}
